.TH ePiX 1 "August 26, 2004"
.LO 1
.fi
.SH NAME
ePiX \- A utility for creating mathematically accurate figures
.SH SYNOPSIS
.in +7n
.ti -7n
epix  [options] file[.xp] [outfile[.eepic]]
.P
elaps [options] file[.xp|.eepic]
.P
laps  [options] file[.tex]
.P
flix  [options] file[.flx]
.in -7n
.P 
.SH ONLINE RESOURCES
Project page:

	http://mathcs.holycross.edu/~ahwang/current/ePiX.html

Public CVS server:

	https://savannah.nongnu.org/projects/epix

CTAN:

	http://www.ctan.org/tex-archive/graphics/epix

Mailing list (to subscribe):

	ahwang-epix-subscribe@mathcs.holycross.edu

.SH DOCUMENTATION
Sample files and an extensive tutorial introduction/reference manual
come with the source code. Please look in
.B /usr/local/share/epix
for these materials. The documentation can be downloaded in several
formats from the project page. 

.SH "AUTHOR"
.nf
.na
Andrew D. Hwang (rot 13: nujnat at zngupf dot ubylpebff dot rqh)
Department of Mathematics and Computer Science
College of the Holy Cross
Worcester, MA 01610-2395, USA
