#! /bin/sh

###########################################################################
#                                                                         #
# keywords -- simple lookup script for C/C++ keywords                     #
#                                                                         #
# C++ keywords taken from "The C++ programming language, Special edition" #
# Bjarne Stroustrup, Copyright (C) 1997, Addison-Wesley, p. 794           #
#                                                                         #
# C keywords taken from "The C programming language, 2nd (ANSI) edition"  #
# Brian Kernighan and Dennis Ritchie, (C) 1988, Prentice-Hall, p. 192     #
#                                                                         #
###########################################################################

for i in ${1+"$@"}; do grep "$i" "$0" | grep -v "\#"; done; exit 0
#########################################################################
#                        C++ reserved words                             #
#########################################################################

and		C++
and_eq		C++
asm		C++
auto		C++

bitand		C++
bitor		C++
bool		C++
break		C++

case		C++
catch		C++
char		C++
class		C++
compl		C++
const		C++
const_cast	C++
continue	C++

default		C++
delete		C++
do		C++
double		C++
dynamic_cast	C++

else		C++
enum		C++
explicit	C++
export		C++
extern		C++

faslse		C++
float		C++
for		C++
friend		C++

goto		C++

if		C++
inline		C++
int		C++

long		C++

mutable		C++

namespace	C++
new		C++
not		C++
not_eq		C++

operator	C++
or		C++
or_eq		C++

private		C++
protected	C++
public		C++

register	C++
reinterpret_cast C++
return		C++

short		C++
signed		C++
sizeof		C++
static		C++
static_cast	C++
struct		C++
switch		C++

template	C++
this		C++
throw		C++
true		C++
try		C++
typedef		C++
typeid		C++
typename	C++

union		C++
unsigned	C++
using		C++

virtual		C++
void		C++
volatile	C++

wchar_t		C++
while		C++

xor		C++
xor_eq		C++

#########################################################################
#                         C reserved words                              #
#########################################################################

auto		C

break		C

case		C
char		C
const		C
continue	C

default		C
do		C
double		C

else		C
enum		C
extern		C

float		C
for		C

goto		C

if		C
int		C

long		C

register	C
return		C

short		C
signed		C
sizeof		C
static		C
struct		C
switch		C

typedef		C

union		C
unsigned	C

void		C
volatile	C

while		C
