#!/usr/bin/env bash
# format.sh -- format the whole tree in place. Run via `make format`, and
# automatically when you exit `make shell`.
#
#   C++    : clang-format (.clang-format, google style). Applied tree-wide,
#            INCLUDING the upstream libepix sources -- Bill granted an explicit
#            exception to the mirror-preservation rule for formatting.
#   Python : ruff lint-fix + format (config in python/pyproject.toml).
#
# The generated umbrella header epix.h is skipped (it's regenerated by make_header).
cd /epix

echo "clang-format (C++) ..."
find src include/epix python/epix build-aux \
     \( -name '*.cc' -o -name '*.h' \) ! -name 'epix.h' -print0 \
    | xargs -0 -r clang-format -i

echo "ruff (Python) ..."
RUFF_CFG=python/pyproject.toml
ruff check --fix --config "$RUFF_CFG" . >/dev/null 2>&1 || true
ruff format --config "$RUFF_CFG" . || true

echo "formatted."
