#!/bin/bash
#
HEADERS="constants.h functions.h Position.h Vector.h Pair.h Camera.h Color.h"

echo "/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\ " > epix.h
echo " *  epix.h -- Automatically created on $(date)  * " >> epix.h
echo "\* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */ " >> epix.h
echo "" >> epix.h

cat $HEADERS | grep -v "\#if" | grep -v "include \"" | grep -v "_INCLUDE" \
	     | grep -v "endif" | grep -v "const char \*epix_version" >> epix.h
exit 0;
