#!/bin/bash
#
OUTPUT_FILE=epix2.h

SRC_INT=src/Internals
SRC_OUT=src/Output
SRC_PIC=src/Picture
SRC_WOR=src/World

cat <<HEADER_HEADER > $OUTPUT_FILE
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\\
 * $OUTPUT_FILE -- Automatically created on $(date)  *
\* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#ifndef EPIX2_HEADER_FILE
#define EPIX2_HEADER_FILE

#include <iostream>
#include <sstream>
#include <list>
#include <vector>
#include <set>
#include <cstdlib>
#include <cmath>

#ifndef EPIX2_ERRORS
#include "$SRC_INT/Errors.h"
#endif
#ifndef EPIX2_CONSTANTS
#include "$SRC_INT/Constants.h"
#endif

#ifndef EPIX2_LENGTHS
#include "$SRC_INT/Length.h"
#endif
#ifndef EPIX2_COLOR
#include "$SRC_INT/Color.h"
#endif
#ifndef EPIX2_STYLES
#include "$SRC_INT/Styles.h"
#endif

#ifndef EPIX2_PAIR
#include "$SRC_INT/Pair.h"
#endif
#ifndef EPIX2_PAIR_MAP
#include "$SRC_INT/Pair_Map.h"
#endif
#ifndef EPIX2_POINT
#include "$SRC_INT/Point.h"
#endif
#ifndef EPIX2_FUNCTIONS
#include "$SRC_INT/Functions.h"
#endif
#ifndef EPIX2_CHOP
#include "$SRC_INT/Chop.h"
#endif
#ifndef EPIX2_VISIBILITY
#include "$SRC_INT/Visibility.h"
#endif

#ifndef EPIX2_VECTOR
#include "$SRC_INT/Vector.h"
#endif
#ifndef EPIX2_BASIS
#include "$SRC_INT/Basis.h"
#endif
#ifndef EPIX2_CAMERA
#include "$SRC_INT/Camera.h"
#endif

#ifndef EPIX2_TILE
#include "$SRC_PIC/Tile.h"
#endif
#ifndef EPIX2_OUTLINE
#include "$SRC_PIC/Outline.h"
#endif
#ifndef EPIX2_SILHOUETTE
#include "$SRC_PIC/Silhouette.h"
#endif
#ifndef EPIX2_TEXT2
#include "$SRC_PIC/Text2.h"
#endif
#ifndef EPIX2_SCREEN
#include "$SRC_PIC/Screen.h"
#endif
#ifndef EPIX2_PICTURE
#include "$SRC_PIC/Picture.h"
#endif

#ifndef EPIX2_OUTPUT
#include "$SRC_OUT/Output.h"
#endif
#ifndef EPIX2_PSTRICKS
#include "$SRC_OUT/PSTricks.h"
#endif
#ifndef EPIX2_PS
#include "$SRC_OUT/PS.h"
#endif

#ifndef EPIX2_OBJECT
#include "$SRC_WOR/Object.h"
#endif
#ifndef EPIX2_OBJECT_REP
#include "$SRC_WOR/Object_Rep.h"
#endif
#ifndef EPIX2_PATH_BASE
#include "$SRC_WOR/Path_Base.h"
#endif
#ifndef EPIX2_PATH_REP
#include "$SRC_WOR/Path_Rep.h"
#endif
#ifndef EPIX2_SURFACE_BASE
#include "$SRC_WOR/Surface_Base.h"
#endif
#ifndef EPIX2_SURFACE_REP
#include "$SRC_WOR/Surface_Rep.h"
#endif
#ifndef EPIX2_TEXT_BASE
#include "$SRC_WOR/Text_Base.h"
#endif
#ifndef EPIX2_TEXT_REP
#include "$SRC_WOR/Text_Rep.h"
#endif
#ifndef EPIX2_TRIANGLE
#include "$SRC_WOR/Triangle.h"
#endif
#ifndef EPIX2_WORLD
#include "$SRC_WOR/World.h"
#endif

#endif // EPIX2_HEADER_FILE
HEADER_HEADER

exit 0;
