#!/bin/bash

# MY_DATE=$(date +"%m.%d.%y_%Hh_%Mm")
MY_DATE=$(date +"%m.%d.%y")

OUTFILE=epix2-${MY_DATE}.tar

if [ -f $OUTFILE.bz2 ]; then
    echo "File $OUTFILE.bz2 exists, no action"

else
    tar -cf - $(cat files | grep -v '#') | bzip2 > $OUTFILE.bz2
fi

exit 0
